spring:
  datasource:
    url: jdbc:mysql://localhost:3306/payment_db
    username: root
    password: Ritesh@07
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  jwt:
    secret: B0WuXA9ruJQDE2B96CYQPfOaIEIV3046NUcTgu+LX8o=
    expiration-ms: 86400000

razorpay:
  key-id: rzp_test_T2IZ25xDYCgJes
  key-secret: h1tz6LfdIfB1Tz9oigCNJAqA
  webhook-secret: placeholder